[package]
name = "b64"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.19", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
